### ISSUE TITLE
Menu dissapears when module enabled

### ISSUE THREAD

**Issue by shopwhizzy** [JaJuMa-GmbH/hyva-pwa#1]
Hi
Menu dissapear in latest magento + hyva version 2.4.6-p2 even if we remove the ttl="3600".
Any insights?

**Comment by JaJuMa** [comment]
Hi @mgtwizards 
Does that happen on a vanilla Magento installation or with other extensions or customization's?
What would be the steps to reproduce?
Can you please try to reproduce on our demo site: [https://hyva.extension.jajuma.de/](https://hyva.extension.jajuma.de/)

**Comment by shopwhizzy** [comment]
Hi @JaJuMa 
I have installed directly at live site and since we faced issues removed instantly.
Today will try at staging and debug a little further.
Server stack is nginx/varnish/redis/PFM with opcache. Maybe some is causing it (perhaps need to modify varnish vcl).
Our magento has some 3rd party modules but i know them deep in and out. Not seeing any that could possible mess with it to be honest.
But i will take a look and let you know.
Thank you for the prompt reply.
Regards

**Comment by JaJuMa** [comment]
Hi @mgtwizards 
maybe we found the issue.
Can you please try [v.1.0.4](https://github.com/JaJuMa-GmbH/hyva-pwa/releases/tag/1.0.4) and see if it works for you?

**Comment by shopwhizzy** [comment]
Hi

I Will take a look and try during the morning.

Ty for letting me know


A quarta, 8/11/2023, 06:55, JaJuMa ***@***.***> escreveu:

**Comment by shopwhizzy** [comment]
@JaJuMa Hi there

Just had a chance to check today.
Worked flawlessly.

Thanks ;)
